wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: torch
    huggingface_version: 3.0.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
